version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./.env
  py-backend:
    restart: always
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
    volumes:
      - ./backend/python:/app
      - file_uploads:/var/lib/file_uploads
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql/
    env_file:
      - ./.env
  test-db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql_test/
    env_file:
      - ./.env

volumes:
  mysql_data:
  mysql_test_data:
  file_uploads:
