version: '3.7'

services:
  py-backend:
    command: /app/tools/wait-for-it.sh test-db:3306 -- ./tools/migrate_and_pytest.sh
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
    volumes:
      - file_uploads:/var/lib/file_uploads
    depends_on:
      - test-db
    env_file:
      - ./.env
  test-db:
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - 3307:3306
    volumes:
      - mysql_test_data:/var/lib/mysql_test/
    env_file:
      - ./.env

volumes:
  mysql_test_data:
  file_uploads:
