version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false
      - run:
          name: Create env file
          command: |
            touch .env
      - run:
          name: Start container via docker-compose
          command: |
            set -x
            docker-compose up -d
  lint:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - checkout
      - run:
          name: Run linter checks
          command: |
            pip install black isort
            echo "Running black checks..."
            black backend/python/app/ --check
            echo "Checking import order..."
            isort --profile black backend/python/app/ -c
            echo "Code properly linted!"

workflows:
  version: 2
  lint and build:
    jobs:
      - lint
      - build:
          requires:
            - lint
