"""Add translator_last_activity and reviewer_last_activity time columns to StoryTranslation model

Revision ID: 01bc39c1accc
Revises: 91e8d22078f4
Create Date: 2021-12-13 00:39:25.688445

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "01bc39c1accc"
down_revision = "91e8d22078f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story_translations_all",
        sa.Column("reviewer_last_activity", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "story_translations_all",
        sa.Column("translator_last_activity", sa.DateTime(), nullable=True),
    )
    active_translations_view = """
        CREATE OR REPLACE VIEW story_translations
        AS
        SELECT * from story_translations_all
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story_translations_all", "translator_last_activity")
    op.drop_column("story_translations_all", "reviewer_last_activity")
    active_translations_view = """
        CREATE OR REPLACE VIEW story_translations
        AS
        SELECT * from story_translations_all
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)
    # ### end Alembic commands ###
