"""Add activity time columns

Revision ID: 04407ca2b4ef
Revises: 04653332ed3a
Create Date: 2021-12-20 00:13:17.086241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "04407ca2b4ef"
down_revision = "04653332ed3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story_translations_all",
        sa.Column("reviewer_last_activity", sa.DateTime(), nullable=True),
    )
    op.add_column(
        "story_translations_all",
        sa.Column("translator_last_activity", sa.DateTime(), nullable=True),
    )
    active_translations_view = """
        CREATE OR REPLACE VIEW story_translations
        AS
        SELECT * from story_translations_all
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story_translations_all", "translator_last_activity")
    op.drop_column("story_translations_all", "reviewer_last_activity")
    active_translations_view = """
        CREATE OR REPLACE VIEW story_translations
        AS
        SELECT * from story_translations_all
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)
    # ### end Alembic commands ###
