"""add story test changes

Revision ID: 04653332ed3a
Revises: 91e8d22078f4
Create Date: 2021-12-10 03:27:03.107768

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "04653332ed3a"
down_revision = "91e8d22078f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stories", sa.Column("is_test", sa.Boolean(), default=False, nullable=False)
    )
    op.add_column(
        "story_translations_all",
        sa.Column("is_test", sa.Boolean(), default=False, nullable=False),
    )
    op.add_column(
        "story_translations_all",
        sa.Column("test_feedback", mysql.TEXT(), nullable=True),
    )
    op.add_column(
        "story_translations_all", sa.Column("test_grade", sa.Float(), nullable=True)
    )
    op.add_column(
        "story_translations_all", sa.Column("test_result", sa.JSON(), nullable=True)
    )

    op.execute(
        "ALTER TABLE story_translation_contents_all MODIFY COLUMN status ENUM('DEFAULT', 'ACTION_REQUIRED', 'APPROVED', 'TEST_CORRECT', 'TEST_PARTIALLY_CORRECT', 'TEST_INCORRECT') NOT NULL;"
    )

    active_translations_view = """
        CREATE OR REPLACE VIEW story_translations
        AS        
        SELECT * from story_translations_all
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story_translations_all", "test_result")
    op.drop_column("story_translations_all", "test_grade")
    op.drop_column("story_translations_all", "test_feedback")
    op.drop_column("story_translations_all", "is_test")
    op.drop_column("stories", "is_test")

    active_translations_view = """
        CREATE OR REPLACE VIEW story_translations
        AS        
        SELECT * from story_translations_all
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)
    # ### end Alembic commands ###
