"""add is_deleted flag to story_translations

Revision ID: 1729015196af
Revises: 5a1dbdb0d816
Create Date: 2021-10-19 04:26:37.069546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1729015196af"
down_revision = "5a1dbdb0d816"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story_translations",
        sa.Column("is_deleted", sa.Boolean(), default=False, nullable=False),
    )
    active_translations_view = """
        CREATE VIEW story_translations_active
        AS        
        SELECT * from story_translations
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("story_translations", "is_deleted")
    op.execute("DROP VIEW story_translations_active")
    # ### end Alembic commands ###
