"""implement soft delete for story_translations

Revision ID: 1729015196af
Revises: 5a1dbdb0d816
Create Date: 2021-10-19 04:26:37.069546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1729015196af"
down_revision = "5a1dbdb0d816"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ### Update story_translations
    op.add_column(
        "story_translations",
        sa.Column("is_deleted", sa.Boolean(), default=False, nullable=False),
    )
    op.drop_constraint(
        u"story_translations_ibfk_1", "story_translations", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_ibfk_2", "story_translations", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_ibfk_3", "story_translations", type_="foreignkey"
    )
    op.rename_table("story_translations", "story_translations_all")
    op.create_foreign_key(
        u"story_translations_all_ibfk_1",
        "story_translations_all",
        "users",
        ["reviewer_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"story_translations_all_ibfk_2",
        "story_translations_all",
        "users",
        ["translator_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"story_translations_all_ibfk_3",
        "story_translations_all",
        "stories",
        ["story_id"],
        ["id"],
    )
    active_translations_view = """
        CREATE VIEW story_translations
        AS        
        SELECT * from story_translations_all
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)

    ### Update story_translation_contents
    op.add_column(
        "story_translation_contents",
        sa.Column("is_deleted", sa.Boolean(), default=False, nullable=False),
    )
    op.drop_constraint(
        u"story_translation_contents_ibfk_1",
        "story_translation_contents",
        type_="foreignkey",
    )
    op.rename_table("story_translation_contents", "story_translation_contents_all")
    op.create_foreign_key(
        u"story_translation_contents_all_ibfk_1",
        "story_translation_contents_all",
        "story_translations_all",
        ["story_translation_id"],
        ["id"],
    )
    active_translation_contents_view = """
        CREATE VIEW story_translation_contents
        AS        
        SELECT * from story_translation_contents_all
        WHERE is_deleted=0;
    """
    op.execute(active_translation_contents_view)

    ### Update comments
    op.add_column(
        "comments",
        sa.Column("is_deleted", sa.Boolean(), default=False, nullable=False),
    )
    op.drop_constraint(
        u"comments_ibfk_1",
        "comments",
        type_="foreignkey",
    )
    op.drop_constraint(
        u"comments_ibfk_2",
        "comments",
        type_="foreignkey",
    )
    op.rename_table("comments", "comments_all")
    op.create_foreign_key(
        u"comments_all_ibfk_1",
        "comments_all",
        "story_translation_contents_all",
        ["story_translation_content_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"comments_all_ibfk_2",
        "comments_all",
        "users",
        ["user_id"],
        ["id"],
    )
    active_comments_view = """
        CREATE VIEW comments
        AS        
        SELECT * from comments_all
        WHERE is_deleted=0;
    """
    op.execute(active_comments_view)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ### Update story_translations
    op.execute("DROP VIEW story_translations")
    op.drop_constraint(
        u"story_translations_all_ibfk_1", "story_translations_all", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_all_ibfk_2", "story_translations_all", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_all_ibfk_3", "story_translations_all", type_="foreignkey"
    )
    op.rename_table("story_translations_all", "story_translations")
    op.create_foreign_key(
        u"story_translations_ibfk_1",
        "story_translations",
        "users",
        ["reviewer_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"story_translations_ibfk_2",
        "story_translations",
        "users",
        ["translator_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"story_translations_ibfk_3",
        "story_translations",
        "stories",
        ["story_id"],
        ["id"],
    )
    op.drop_column("story_translations", "is_deleted")

    ### Update story_translation_contents
    op.execute("DROP VIEW story_translation_contents")
    op.drop_constraint(
        u"story_translation_contents_all_ibfk_1",
        "story_translation_contents_all",
        type_="foreignkey",
    )
    op.rename_table("story_translation_contents_all", "story_translation_contents")
    op.create_foreign_key(
        u"story_translation_contents_ibfk_1",
        "story_translation_contents",
        "story_translations",
        ["story_translation_id"],
        ["id"],
    )
    op.drop_column("story_translation_contents", "is_deleted")

    ### Update comments
    op.execute("DROP VIEW comments")
    op.drop_constraint(
        u"comments_all_ibfk_1",
        "comments_all",
        type_="foreignkey",
    )
    op.drop_constraint(
        u"comments_all_ibfk_2",
        "comments_all",
        type_="foreignkey",
    )
    op.rename_table("comments_all", "comments")
    op.create_foreign_key(
        u"comments_ibfk_1",
        "comments",
        "story_translation_contents",
        ["story_translation_content_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"comments_ibfk_2",
        "comments",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_column("comments", "is_deleted")

    # ### end Alembic commands ###
