"""implement soft delete for story_translations

Revision ID: 1729015196af
Revises: 5a1dbdb0d816
Create Date: 2021-10-19 04:26:37.069546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1729015196af"
down_revision = "5a1dbdb0d816"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "story_translations",
        sa.Column("is_deleted", sa.Boolean(), default=False, nullable=False),
    )
    op.drop_constraint(
        u"story_translations_ibfk_1", "story_translations", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_ibfk_2", "story_translations", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_ibfk_3", "story_translations", type_="foreignkey"
    )
    op.rename_table("story_translations", "story_translations_all")
    op.create_foreign_key(
        u"story_translations_all_ibfk_1",
        "story_translations_all",
        "users",
        ["reviewer_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"story_translations_all_ibfk_2",
        "story_translations_all",
        "users",
        ["translator_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"story_translations_all_ibfk_3",
        "story_translations_all",
        "stories",
        ["story_id"],
        ["id"],
    )

    active_translations_view = """
        CREATE VIEW story_translations
        AS        
        SELECT * from story_translations_all
        WHERE is_deleted=0;
    """
    op.execute(active_translations_view)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW story_translations")
    op.drop_constraint(
        u"story_translations_all_ibfk_1", "story_translations_all", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_all_ibfk_2", "story_translations_all", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_all_ibfk_3", "story_translations_all", type_="foreignkey"
    )
    op.rename_table("story_translations_all", "story_translations")
    op.create_foreign_key(
        u"story_translations_ibfk_1",
        "story_translations",
        "users",
        ["reviewer_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"story_translations_ibfk_2",
        "story_translations",
        "users",
        ["translator_id"],
        ["id"],
    )
    op.create_foreign_key(
        u"story_translations_ibfk_3",
        "story_translations",
        "stories",
        ["story_id"],
        ["id"],
    )
    op.drop_column("story_translations", "is_deleted")

    # ### end Alembic commands ###
