"""add email to user table

Revision ID: 1d3513a3aff7
Revises: e59c40e297d1
Create Date: 2021-10-12 15:23:18.651050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d3513a3aff7'
down_revision = 'e59c40e297d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'email', 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
