"""initial migration

Revision ID: 3f6fff20884c
Revises: 
Create Date: 2021-08-30 16:07:51.455852

"""
import os

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "3f6fff20884c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", mysql.TEXT(), nullable=False),
        sa.Column("last_name", mysql.TEXT(), nullable=False),
        sa.Column("auth_id", mysql.TEXT(), nullable=False),
        sa.Column("role", sa.Enum("User", "Admin", name="roles"), nullable=True),
        sa.Column("resume", sa.Integer(), nullable=True),
        sa.Column("profile_pic", sa.Integer(), nullable=True),
        sa.Column("approved_languages", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_pic"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resume"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", mysql.TEXT(), nullable=False),
        sa.Column("description", mysql.LONGTEXT(), nullable=False),
        sa.Column("youtube_link", mysql.TEXT(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("translated_languages", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "story_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story_id", sa.Integer(), nullable=False),
        sa.Column("line_index", sa.Integer(), nullable=False),
        sa.Column("content", mysql.LONGTEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_contents_story_id"), "story_contents", ["story_id"], unique=False
    )
    op.create_table(
        "story_translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story_id", sa.Integer(), nullable=False),
        sa.Column("language", mysql.TEXT(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum("START", "TRANSLATE", "REVIEW", "PUBLISH", name="stages"),
            nullable=False,
        ),
        sa.Column("translator_id", sa.Integer(), nullable=True),
        sa.Column("reviewer_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["translator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_translations_reviewer_id"),
        "story_translations",
        ["reviewer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_story_translations_translator_id"),
        "story_translations",
        ["translator_id"],
        unique=False,
    )

    op.create_table(
        "story_translation_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story_translation_id", sa.Integer(), nullable=False),
        sa.Column("line_index", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "name",
                "DEFAULT",
                "ACTION_REQUIRED",
                "APPROVED",
                name="storytranslationcontentstatus",
            ),
            server_default="DEFAULT",
            nullable=False,
        ),
        sa.Column("translation_content", mysql.LONGTEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_translation_id"],
            ["story_translations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_story_translation_contents_story_translation_id"),
        "story_translation_contents",
        ["story_translation_id"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("story_translation_content_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment_index", sa.Integer(), nullable=False),
        sa.Column("time", mysql.DATETIME(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("content", mysql.LONGTEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["story_translation_content_id"],
            ["story_translation_contents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_comments_story_translation_content_id"),
        "comments",
        ["story_translation_content_id"],
        unique=False,
    )
    ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u"users_ibfk_1", "users", type_="foreignkey")
    op.drop_constraint(u"users_ibfk_2", "users", type_="foreignkey")
    op.drop_constraint(u"story_contents_ibfk_1", "story_contents", type_="foreignkey")
    op.drop_constraint(
        u"story_translations_ibfk_1", "story_translations", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_ibfk_2", "story_translations", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translations_ibfk_3", "story_translations", type_="foreignkey"
    )
    op.drop_constraint(
        u"story_translation_contents_ibfk_1",
        "story_translation_contents",
        type_="foreignkey",
    )
    op.drop_constraint(u"comments_ibfk_1", "comments", type_="foreignkey")
    op.drop_constraint(u"comments_ibfk_2", "comments", type_="foreignkey")
    op.drop_index(
        op.f("ix_comments_story_translation_content_id"), table_name="comments"
    )
    op.drop_table("comments")
    op.drop_index(
        op.f("ix_story_translation_contents_story_translation_id"),
        table_name="story_translation_contents",
    )
    op.drop_table("story_translation_contents")
    op.drop_index(
        op.f("ix_story_translations_translator_id"), table_name="story_translations"
    )
    op.drop_index(
        op.f("ix_story_translations_reviewer_id"), table_name="story_translations"
    )
    op.drop_table("story_translations")
    op.drop_table("users")
    op.drop_index(op.f("ix_story_contents_story_id"), table_name="story_contents")
    op.drop_table("story_contents")
    op.drop_table("stories")
    op.drop_table("files")
    # ### end Alembic commands ###
