"""add email to user table

Revision ID: 5a1dbdb0d816
Revises: e59c40e297d1
Create Date: 2021-10-13 02:19:05.769253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1dbdb0d816'
down_revision = 'e59c40e297d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'email', 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
