"""create languages table

Revision ID: 6bcd31d976d6
Revises: c0622865069d
Create Date: 2021-12-31 22:23:00.847824

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6bcd31d976d6"
down_revision = "c0622865069d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    languages_table = op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language", mysql.TEXT(), nullable=False),
        sa.Column("is_rtl", sa.Boolean(), nullable=True, default=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(
        languages_table,
        [
            {"language": "ARABIC", "is_rtl": True},
            {"language": "ASANTE TWI", "is_rtl": False},
            {"language": "ASSAMESE", "is_rtl": False},
            {"language": "BENGALI", "is_rtl": False},
            {"language": "BHILI", "is_rtl": False},
            {"language": "CATALAN", "is_rtl": False},
            {"language": "CHATINO", "is_rtl": False},
            {"language": "DANISH", "is_rtl": False},
            {"language": "DUTCH", "is_rtl": False},
            {"language": "ENGLISH_UK", "is_rtl": False},
            {"language": "ENGLISH_US", "is_rtl": False},
            {"language": "ENGLISH_INDIAN", "is_rtl": False},
            {"language": "ESPERANTO", "is_rtl": False},
            {"language": "FRENCH", "is_rtl": False},
            {"language": "GEORGIAN", "is_rtl": False},
            {"language": "GERMAN", "is_rtl": False},
            {"language": "GREEK", "is_rtl": False},
            {"language": "GUJARATI", "is_rtl": False},
            {"language": "HEBREW", "is_rtl": True},
            {"language": "HINDI", "is_rtl": False},
            {"language": "INDONESIAN", "is_rtl": False},
            {"language": "ITALIAN", "is_rtl": False},
            {"language": "JAPANESE", "is_rtl": False},
            {"language": "KANNADA", "is_rtl": False},
            {"language": "KAZAKH", "is_rtl": False},
            {"language": "KHMER", "is_rtl": False},
            {"language": "KOTAVA", "is_rtl": False},
            {"language": "KURDISH", "is_rtl": True},
            {"language": "KUTCHI", "is_rtl": False},
            {"language": "LIDEPLA", "is_rtl": False},
            {"language": "MALAYALAM", "is_rtl": False},
            {"language": "MALTESE", "is_rtl": False},
            {"language": "MANDARIN", "is_rtl": False},
            {"language": "MARATHI", "is_rtl": False},
            {"language": "NEPALI", "is_rtl": False},
            {"language": "NORWEGIAN", "is_rtl": False},
            {"language": "ORIYA", "is_rtl": False},
            {"language": "POLISH", "is_rtl": False},
            {"language": "PORTUGUESE", "is_rtl": False},
            {"language": "PUNJABI", "is_rtl": False},
            {"language": "ROMANIAN", "is_rtl": False},
            {"language": "RUSSIAN", "is_rtl": False},
            {"language": "SANSKRIT", "is_rtl": False},
            {"language": "SANTALI", "is_rtl": False},
            {"language": "SPANISH", "is_rtl": False},
            {"language": "SWAHILI", "is_rtl": False},
            {"language": "TAMANG", "is_rtl": False},
            {"language": "TAMIL", "is_rtl": False},
            {"language": "TELUGU", "is_rtl": False},
            {"language": "TURKISH", "is_rtl": False},
            {"language": "UKRAINIAN", "is_rtl": False},
            {"language": "URDU", "is_rtl": True},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("languages")
    # ### end Alembic commands ###
