"""add additional_experiences column to user

Revision ID: 91e8d22078f4
Revises: 92ace1398b9f
Create Date: 2021-12-01 03:38:15.575681

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "91e8d22078f4"
down_revision = "92ace1398b9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users_all", sa.Column("additional_experiences", sa.JSON(), nullable=True)
    )
    op.execute("DROP VIEW users")
    active_users_view = """
        CREATE VIEW users
        AS        
        SELECT * from users_all
        WHERE is_deleted=0;
    """
    op.execute(active_users_view)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW users")
    op.drop_column("users_all", "additional_experiences")
    active_users_view = """
        CREATE VIEW users
        AS        
        SELECT * from users_all
        WHERE is_deleted=0;
    """
    op.execute(active_users_view)
    # ### end Alembic commands ###
