"""add date_uploaded to stories

Revision ID: b6b3b28741b9
Revises: 04407ca2b4ef
Create Date: 2021-12-21 19:21:11.449605

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6b3b28741b9"
down_revision = "04407ca2b4ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("stories", sa.Column("date_uploaded", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stories", "date_uploaded")
    # ### end Alembic commands ###
