"""soft delete stories

Revision ID: c0622865069d
Revises: b6b3b28741b9
Create Date: 2021-12-26 19:13:49.635753

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c0622865069d"
down_revision = "b6b3b28741b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # stories
    op.add_column(
        "stories",
        sa.Column("is_deleted", sa.Boolean(), default=False, nullable=False),
    )
    op.drop_constraint(
        "story_translations_all_ibfk_3", "story_translations_all", type_="foreignkey"
    )

    op.rename_table("stories", "stories_all")

    op.create_foreign_key(
        u"story_translations_all_ibfk_3",
        "story_translations_all",
        "stories_all",
        ["story_id"],
        ["id"],
    )

    active_stories_view = """
        CREATE VIEW stories 
        AS 
        SELECT * FROM stories_all
        WHERE is_deleted=0;
    """
    op.execute(active_stories_view)

    # story_contents
    op.add_column(
        "story_contents",
        sa.Column("is_deleted", sa.Boolean(), default=False, nullable=False),
    )

    op.drop_constraint("story_contents_ibfk_1", "story_contents", type_="foreignkey")

    op.drop_index("ix_story_contents_story_id", table_name="story_contents")

    op.rename_table("story_contents", "story_contents_all")

    op.create_index(
        op.f("ix_story_contents_all_story_id"),
        "story_contents_all",
        ["story_id"],
        unique=False,
    )

    op.create_foreign_key(
        u"story_contents_all_ibfk_1",
        "story_contents_all",
        "stories_all",
        ["story_id"],
        ["id"],
    )

    active_story_contents_view = """
        CREATE VIEW story_contents 
        AS 
        SELECT * FROM story_contents_all
        WHERE is_deleted=0;
    """

    op.execute(active_story_contents_view)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # stories
    op.execute("DROP VIEW stories")

    op.drop_constraint(
        "story_translations_all_ibfk_3", "story_translations_all", type_="foreignkey"
    )

    op.rename_table("stories_all", "stories")

    op.create_foreign_key(
        u"story_translations_all_ibfk_3",
        "story_translations_all",
        "stories",
        ["story_id"],
        ["id"],
    )

    op.drop_column("stories", "is_deleted")

    # story_contents
    op.execute("DROP VIEW story_contents")

    op.drop_constraint(
        "story_contents_all_ibfk_1", "story_contents_all", type_="foreignkey"
    )

    op.drop_index("ix_story_contents_all_story_id", table_name="story_contents_all")

    op.rename_table("story_contents_all", "story_contents")

    op.create_foreign_key(
        u"story_contents_ibfk_1",
        "story_contents",
        "stories",
        ["story_id"],
        ["id"],
    )

    op.create_index(
        op.f("ix_story_contents_story_id"),
        "story_contents",
        ["story_id"],
        unique=False,
    )

    op.drop_column("story_contents", "is_deleted")

    # ### end Alembic commands ###
