"""add user auth_id unique constraint

Revision ID: c29196f789b5
Revises: 3f6fff20884c
Create Date: 2021-09-06 16:30:17.662080

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c29196f789b5"
down_revision = "3f6fff20884c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "auth_id",
        existing_type=mysql.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "users", ["auth_id"])
    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u"auth_id", "users", type_="unique")
    op.alter_column(
        "users",
        "auth_id",
        existing_type=sa.String(length=100),
        type_=mysql.TEXT(),
        existing_nullable=False,
    )
    ### end Alembic commands ###
